### ISSUE TITLE
Write test for backpropagation using simple example

### ISSUE THREAD

**Issue by PaulaRudy** [PaulaRudy/FSON#11]

**Comment by PaulaRudy** [comment]
Dependent on #10

**Comment by madhephaestus** [comment]
You may want to look at ZenHub plugin for Chrome/Firefox to do dependant issues/SCRUM. https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US
