### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by PaulaRudy** [PaulaRudy/FSON#15]
Remove accidentally committed stuff (bin), update gitignore

**Comment by madhephaestus** [comment]
This is the process i was talking about to rebase  Git repo to fix the author of all the commits. It is what i uses to fix my git repos when i imported them into github in the first place. 

http://stackoverflow.com/questions/750172/change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-git

**Comment by PaulaRudy** [comment]
Done as of commit 5a3d6681bb61df73ac21253e9a19ebc7f1b2890a
